services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - frontend-net
    depends_on:
      - simple_python_app

  simple_python_app:
    build: ./simple_python_app
    environment:
      API_DB_HOST: db
      API_DB_PASS: apipass
      API_DB_NAME: api
      API_DB_USER: apiuser
    networks:
      - frontend-net
      - backend-net
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: apipass
      POSTGRES_DB: api
      POSTGRES_USER: apiuser
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  frontend-net:
  backend-net:

volumes:
  dbdata:
