

services:
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
